// A repository path rename stays on the same origin. Keep every storage key
// and exercise a player's previous save through the old and new URL paths.
export default async function namingSmoke(page,url='http://127.0.0.1:5176/'){
  await page.addInitScript(()=>{const Native=window.AudioContext;window.__nameAudio=[];window.AudioContext=class extends Native{constructor(...args){super({...args[0],sinkId:{type:'none'}});window.__nameAudio.push(this);}};});
  await page.setViewportSize({width:390,height:844});await page.goto(url);await page.locator('#start-silent').click();
  const previous=await page.evaluate(async()=>{const {createTown,build}=await import('./src/core.js?v=0.6.8'),{createTown:legacyTown}=await import('./src/legacy-core.js?v=0.6.2'),town=createTown();build(town,'garden',12,7);build(town,'bell',14,8);town.scene='evening';town.weather='rain';town.scale='f';town.backing=false;return {town,legacy:JSON.stringify(legacyTown()),original:JSON.stringify({...town,version:3})};});
  const oldUrl=new URL('/demo6/',url),oldResponse=await page.goto(oldUrl.href),oldPath={requested:oldUrl.href,status:oldResponse.status(),final:page.url()};
  await page.evaluate(previous=>{localStorage.setItem('mon.demo6.composition.v2',JSON.stringify(previous.town));localStorage.setItem('mon.demo6.town.v1',previous.legacy);localStorage.setItem('mon.demo6.composition.original.v3',previous.original);},previous);
  await page.goto(url);await page.locator('#start-sound').click();await page.waitForFunction(()=>window.__nameAudio.some(c=>c.state==='running'&&c.currentTime>.1));
  if(await page.locator('#sound-button').getAttribute('aria-pressed')!=='true')throw Error('Audio cannot start at the new path.');await page.locator('#sound-button').click();if(await page.locator('#sound-button').getAttribute('aria-pressed')!=='false')throw Error('Audio cannot be muted.');
  const inspect=()=>page.evaluate(()=>{const t=JSON.parse(localStorage.getItem('mon.demo6.composition.v2'));return {cells:t.cells,scene:t.scene,weather:t.weather,scale:t.scale,backing:t.backing};}),expected=JSON.stringify(Object.fromEntries(['cells','scene','weather','scale','backing'].map(k=>[k,previous.town[k]])));
  if(JSON.stringify(await inspect())!==expected)throw Error('The new path did not inherit the old town.');
  const title=await page.title();if(title!=='シーケンサータウン / Sequencer Town — mon'||await page.locator('.brand small').textContent()!=='シーケンサータウン'||await page.locator('link[rel=canonical]').getAttribute('href')!=='https://monnouchi.github.io/sequencer-town/'||await page.locator('meta[property="og:url"]').getAttribute('content')!=='https://monnouchi.github.io/sequencer-town/')throw Error('Official name or metadata still use the previous name.');
  const views=[];for(const [width,height]of [[1280,900],[320,400],[320,568],[390,844]]){await page.setViewportSize({width,height});await page.waitForTimeout(50);const frame=await page.evaluate(()=>({width:innerWidth,overflow:document.documentElement.scrollWidth>innerWidth,brand:document.querySelector('.brand').getBoundingClientRect().right,actions:document.querySelector('.top-actions').getBoundingClientRect().left}));if(frame.overflow||frame.brand>frame.actions)throw Error('The new name crowds the controls: '+JSON.stringify(frame));views.push(frame);}
  await page.screenshot({path:'output/playwright/sequencer-town-name-390.png'});
  await page.locator('#menu-button').click();const exporting=page.waitForEvent('download');await page.locator('#export-button').click();const exported=await exporting;if(exported.suggestedFilename()!=='sequencer-town.json')throw Error('The save filename still uses the working name.');let raw='';for await(const part of await exported.createReadStream())raw+=part;const t=JSON.parse(raw);if(JSON.stringify(Object.fromEntries(['cells','scene','weather','scale','backing'].map(k=>[k,t[k]])))!==expected)throw Error('Export altered the saved town.');await page.locator('#menu-done').click();
  await page.locator('#photo-button').click();await page.waitForFunction(()=>!document.querySelector('#photo-download').disabled);await page.locator('#photo-framing').selectOption('whole');await page.waitForFunction(()=>!document.querySelector('#photo-download').disabled&&document.querySelector('#photo-preview').naturalWidth===2176);const downloading=page.waitForEvent('download');await page.locator('#photo-download').click();const photo=await downloading;if(photo.suggestedFilename()!=='sequencer-town.png')throw Error('The photo filename still uses the working name.');await photo.saveAs('output/playwright/sequencer-town-name-photo.png');await page.locator('#photo-dialog .dialog-close').click();
  await page.reload();await page.locator('#start-silent').click();if(JSON.stringify(await inspect())!==expected)throw Error('The old town was lost on reload.');const intact=await page.evaluate(previous=>localStorage.getItem('mon.demo6.town.v1')===previous.legacy&&localStorage.getItem('mon.demo6.composition.original.v3')===previous.original,previous);if(!intact)throw Error('The path rename overwrote a previous save or original backup.');
  return {title,oldPath,storageKeysPreserved:true,previousTownInherited:true,previousBackupIntact:true,reload:true,audioStarted:true,muted:true,audioSink:'none (real Chrome clock; speaker listening excluded)',views,export:exported.suggestedFilename(),photo:{name:photo.suggestedFilename(),width:2176,height:1332}};
}
