import test from 'node:test';
import assert from 'node:assert/strict';
import { WIDTH,HEIGHT,TYPES,createTown,build,moveBuilding,undoChanges,waterNetwork,previewAction,advance,restoreTown,noteFor,lineCells } from '../src/core.js';
import { scoreAt,accompanimentAt,midiHz,TownAudio,voiceProfile } from '../src/music.js';
import { createTown as oldTown,restoreTown as restoreOld } from '../src/legacy-core.js';
const put=(t,type,x,y)=>{const r=build(t,type,x,y);assert.equal(r.ok,true,r.reason);return r.change;};
function bare(){const t=createTown();t.cells=Array(WIDTH*HEIGHT).fill(null);t.cells[4*WIDTH]={type:'spring'};return t;}
function phrase(){const t=createTown();put(t,'gutter',1,3);put(t,'bell',4,3);put(t,'canal',5,4);put(t,'gutter',5,3);return t;}
function oldComposition(){const t=createTown();t.version=2;put(t,'garden',10,7);delete t.cells[7*WIDTH+10].enabled;t.wood=192;Object.assign(t,{placed:true,heard:true,moved:true,listenTicks:16,completed:true});return t;}
test('starter and save carry no budget or forced completion',()=>{const t=createTown();assert.equal(waterNetwork(t).activeCount,1);assert.equal(scoreAt(2,waterNetwork(t)).length,1);assert.equal('wood' in t,false);assert.equal('completed' in t,false);for(let i=0;i<200;i++)advance(t,1);assert.equal('wood' in t,false);});
test('move changes beat and pitch; undo restores arrangement',()=>{const t=createTown();put(t,'canal',3,5);const before=scoreAt(2,waterNetwork(t))[0],m=moveBuilding(t,[2,5],[3,6]);assert.equal(m.ok,true);const n=waterNetwork(t);assert.equal(scoreAt(2,n).length,0);assert.equal(scoreAt(3,n)[0].note,noteFor(t,6,'mill'));assert.notEqual(scoreAt(3,n)[0].note,before.note);assert.equal(undoChanges(t,m.changes),true);assert.equal(t.cells[5*WIDTH+2].type,'mill');});
test('all melody instruments and backing transpose coherently',()=>{const t=phrase(),a=waterNetwork(t);t.scale='f';const b=waterNetwork(t);a.buildings.forEach((n,i)=>assert.equal(b.buildings[i].note-n.note,3));accompanimentAt(0,'d').forEach((e,i)=>assert.equal(accompanimentAt(0,'f')[i].note-e.note,3));});
test('water never runs out and rain preserves the player score',()=>{const t=bare();for(let x=1;x<16;x++)put(t,'canal',x,4);for(let x=0;x<16;x++)put(t,'bell',x,3);const n=waterNetwork(t);assert.equal(n.activeCount,16);assert.equal(n.groups.length,1);const before=scoreAt(0,n);t.elapsed=44;assert.equal(waterNetwork(t).raining,true);assert.deepEqual(scoreAt(0,waterNetwork(t)),before);t.elapsed=60;assert.deepEqual(scoreAt(0,waterNetwork(t)),before);});
test('every chosen chord note plays, with predictable balancing',()=>{const t=bare();for(let y=0;y<9;y++)if(y!==4)put(t,'canal',0,y);for(let y=0;y<9;y++)put(t,'gutter',1,y);const n=waterNetwork(t),notes=scoreAt(1,n);assert.equal(notes.length,9);assert.equal(n.activeCount,9);assert.ok(notes.every(e=>Math.abs(e.gain-.85/Math.sqrt(3))<1e-12));});
test('2, 3 and 4 adjacent melody cells produce a single longer onset',()=>{for(const type of ['mill','gutter','bell'])for(const span of [2,3,4]){const t=bare();put(t,'canal',1,4);for(let x=1;x<=span;x++)put(t,type,x,3);const n=waterNetwork(t),e=scoreAt(1,n)[0];assert.equal(e.span,span);assert.equal(e.members.length,span);assert.equal(n.activeCount,span);assert.equal(scoreAt(2,n).length,0);assert.ok(e.length>=span);assert.ok(e.length>(type==='bell'?4:type==='mill'?1.3:1.7));}});
test('longhouse crossing bar boundary joins, loop boundary never wraps',()=>{const t=bare();for(let x=1;x<16;x++)put(t,'canal',x,4);for(const x of [0,7,8,15])put(t,'gutter',x,3);const n=waterNetwork(t);assert.equal(n.groups.length,3);assert.equal(scoreAt(7,n)[0].span,2);assert.equal(scoreAt(8,n).length,0);assert.equal(scoreAt(15,n)[0].span,1);assert.equal(scoreAt(16,n)[0].span,1);});
test('OFF, remove and move split longhouses; undo reunites them',()=>{for(const action of ['flow','remove','move']){const t=bare();put(t,'canal',1,4);put(t,'canal',2,4);put(t,'canal',3,4);for(let x=1;x<=3;x++)put(t,'gutter',x,3);const saved=JSON.stringify(t),r=action==='move'?moveBuilding(t,[2,3],[2,2]):build(t,action,2,3);assert.equal(r.ok,true);const n=waterNetwork(t);assert.equal(n.groups.filter(g=>g.active).length,2);assert.equal(undoChanges(t,r.changes??[r.change]),true);assert.equal(JSON.stringify(t),saved);}});
test('one connected member feeds the longhouse; closed branch disconnects it',()=>{const t=bare();put(t,'canal',1,4);for(let x=1;x<=4;x++)put(t,'gutter',x,3);assert.equal(waterNetwork(t).activeCount,4);const c=put(t,'flow',1,4);assert.equal(waterNetwork(t).activeCount,0);undoChanges(t,[c]);assert.equal(waterNetwork(t).activeCount,4);});
test('wood and flowers are independent percussion, consecutive cells retrigger',()=>{const t=bare();for(const type of ['tree','garden'])for(let x=4;x<7;x++)put(t,type,x,type==='tree'?1:2);const n=waterNetwork(t);assert.equal(n.activeCount,6);for(let x=4;x<7;x++)assert.equal(scoreAt(x,n).length,2);const c=put(t,'flow',5,2);assert.equal(scoreAt(5,waterNetwork(t)).length,1);undoChanges(t,[c]);assert.equal(scoreAt(5,waterNetwork(t)).length,2);});
test('all free cells can be filled, removed and undo restores them',()=>{const t=createTown();for(let y=0;y<9;y++)for(let x=0;x<16;x++)if(!t.cells[y*16+x])put(t,'tree',x,y);assert.equal(t.cells.filter(Boolean).length,144);assert.ok(waterNetwork(t).activeCount>100);const original=JSON.stringify(t),changes=[];for(let y=0;y<9;y++)for(let x=0;x<16;x++)if(t.cells[y*16+x]?.type!=='spring')changes.push(put(t,'remove',x,y));undoChanges(t,changes);assert.equal(JSON.stringify(t),original);});
test('preview never mutates state; occupied target and spring are protected',()=>{const t=phrase(),saved=JSON.stringify(t);assert.equal(previewAction(t,'garden',15,8).ok,true);assert.equal(build(t,'canal',0,4).ok,false);assert.equal(build(t,'constructor',1,1).ok,false);assert.equal(moveBuilding(t,[2,5],[1,4]).ok,false);assert.equal(JSON.stringify(t),saved);});
test('v2 migration preserves cells and tuning, leaves old flowers OFF, no duplicate credit',()=>{const old=oldComposition(),raw=JSON.stringify(old),t=restoreTown(JSON.parse(raw));assert.equal(t.version,3);assert.equal(t.cells[7*16+10].enabled,false);assert.equal('wood' in t,false);assert.equal('completed' in t,false);assert.equal(t.cells[5*16+2].enabled,true);assert.equal(JSON.stringify(old),raw);assert.deepEqual(restoreTown(t),t);assert.deepEqual(restoreTown(old),t);assert.throws(()=>restoreTown({...old,wood:198}));});
test('v3 saves round-trip; invalid schema, cell settings and injection are rejected',()=>{const t=phrase();put(t,'tree',0,0);assert.deepEqual(restoreTown(JSON.parse(JSON.stringify(t))),t);for(const c of [{elapsed:Infinity},{scale:'__proto__'},{scene:'<script>'},{version:99},{cells:[]}])assert.throws(()=>restoreTown({...t,...c}));const bad=structuredClone(t);bad.cells[0]={type:'spring'};assert.throws(()=>restoreTown(bad));assert.throws(()=>restoreTown(oldTown()));});
test('v1 archive remains untouched and readable',()=>{const old=oldTown();old.wood=999999;old.growth=999;delete old.arrangement;const raw=JSON.stringify(old),restored=restoreOld(JSON.parse(raw));assert.equal(restored.wood,999999);assert.equal(restored.growth,999);assert.equal(JSON.stringify(old),raw);});
test('2000 random edits preserve score, cells and save round trips',()=>{const t=createTown(),history=[];let seed=321;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/2**32;};for(let i=0;i<2000;i++){if(rand()<.18&&history.length)undoChanges(t,history.pop());else{const r=build(t,Object.keys(TYPES)[Math.floor(rand()*9)],Math.floor(rand()*16),Math.floor(rand()*9));if(r.ok)history.push([r.change]);}advance(t,rand());const n=waterNetwork(t);assert.ok(n.beatCounts.every(v=>v<=9));assert.equal(n.groups.reduce((sum,g)=>sum+g.members.length,0),n.buildings.filter(b=>b.enabled).length);if(i%50===0)assert.deepEqual(restoreTown(JSON.parse(JSON.stringify(t))),t);}assert.deepEqual(lineCells([1,4],[3,2]),[[2,4],[3,4],[3,3],[3,2]]);});
test('score loops, authored harmony stays finite, and visual callbacks follow audio clock',()=>{const t=phrase(),n=waterNetwork(t);for(let i=0;i<64;i++){assert.deepEqual(scoreAt(i,n),scoreAt(i+16,n));for(const e of [...scoreAt(i,n),...accompanimentAt(i,t.scale)])assert.ok(Number.isFinite(midiHz(e.note))&&e.length>0&&e.gain>0);}const calls=[],audio=new TownAudio((s,ns)=>calls.push([s,ns.length]));audio.context={state:'running',currentTime:0};audio.nextTime=.05;audio.setTown(t,n);audio.schedule();assert.equal(audio.voices,0);assert.equal(calls.length,0);audio.context.currentTime=.051;audio.flushVisuals();assert.deepEqual(calls,[[0,0]]);});
test('high voicing softens attack and metal without removing selected fundamental',()=>{for(const type of ['gutter','bell']){const low=voiceProfile(type,62),high=voiceProfile(type,84);assert.ok(high.attack>low.attack);assert.ok(high.volume<low.volume);assert.deepEqual(high.partials[0],[1,'sine',1]);assert.ok(high.partials.at(-1)[2]<low.partials.at(-1)[2]);for(let note=57;note<=84;note++)assert.ok(voiceProfile(type,note).attack>0);}});
test('current feedback and future OFF/ON preview remain distinct',async()=>{const {currentCellCopy,previewCopy,movedCellCopy}=await import('../src/feedback.js');const t=createTown();put(t,'gutter',3,3);moveBuilding(t,[3,3],[3,2]);assert.match(movedCellCopy(t,waterNetwork(t),[3,2]),/水路を伸ばそう/);assert.match(currentCellCopy(t,waterNetwork(t),[3,2]),/^現在：雨樋 · E5/);put(t,'canal',3,3);put(t,'flow',3,2);assert.match(currentCellCopy(t,waterNetwork(t),[3,2]),/音を止めています/);assert.match(previewCopy(previewAction(t,'flow',3,2),'flow',[3,2]),/^切替後：E5.*この拍で鳴ります/);});
test('building photo framing keeps every building inside a padded 4:3 view',async()=>{
  const {frameForBounds}=await import('../src/photo.js'),full={x:0,y:0,width:1088,height:666},bounds=[{x:31,y:218,width:380,height:193}];
  const f=frameForBounds(full,bounds);assert.equal(f.cropped,true);assert.ok(Math.abs(f.width/f.height-4/3)<1e-10);
  assert.ok(f.x>=0&&f.y>=0&&f.x+f.width<=1088&&f.y+f.height<=666);
  for(const b of bounds)assert.ok(f.x<=b.x&&f.y<=b.y&&f.x+f.width>=b.x+b.width&&f.y+f.height>=b.y+b.height);
});
test('a spread-out town and a legacy picture safely fall back to their whole view',async()=>{
  const {frameForBounds}=await import('../src/photo.js'),full={x:0,y:0,width:1088,height:666};
  assert.deepEqual(frameForBounds(full,[]),{...full,cropped:false});
  assert.deepEqual(frameForBounds(full,[{x:32,y:50,width:1000,height:540}]),{...full,cropped:false});
});
